# Write your MySQL query statement below

WITH TEMP AS (
SELECT CONTEST_ID, GOLD_MEDAL AS MEDAL FROM CONTESTS
UNION ALL 
SELECT CONTEST_ID, SILVER_MEDAL FROM CONTESTS
UNION ALL 
SELECT CONTEST_ID, BRONZE_MEDAL FROM CONTESTS),

TEMPB AS (SELECT DISTINCT T1.MEDAL FROM TEMP T1
LEFT JOIN TEMP T2
ON T1.CONTEST_ID = T2.CONTEST_ID - 1
LEFT JOIN TEMP T3
ON T1.CONTEST_ID = T3.CONTEST_ID - 2
WHERE T1.MEDAL = T2.MEDAL AND T1.MEDAL = T3.MEDAL AND T2.MEDAL = T3.MEDAL
UNION ALL
(SELECT GOLD_MEDAL FROM CONTESTS GROUP BY GOLD_MEDAL HAVING COUNT(*) >=3))

SELECT DISTINCT NAME, MAIL FROM USERS U
INNER JOIN TEMPB T
ON U.USER_ID = T.MEDAL;
